{
 "title": "Proxmox Overview",
 "description": "Proxmox Virtual Environment Dashboard",
 "tags": [
  "Proxmox",
  "Prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(pve_node_info, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Resource allocation summary",
   "type": "table",
   "gridPos": { "h": 11, "w": 20, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (id, name, type) (pve_guest_info{instance=\"$instance\",template!=\"1\"})"
    },
    {
     "expr": "sum by (id) (pve_up{instance=\"$instance\"} and on (id, instance) pve_guest_info{template!=\"1\"})"
    },
    {
     "expr": "sum by (id) (pve_cpu_usage_limit{instance=\"$instance\"} and on (id, instance) pve_guest_info{template!=\"1\"})"
    },
    {
     "expr": "sum by (id) (pve_memory_size_bytes{instance=\"$instance\"} and on (id, instance) pve_guest_info{template!=\"1\"})"
    },
    {
     "expr": "sum by (id) (pve_memory_usage_bytes{instance=\"$instance\"} / pve_memory_size_bytes and on (id, instance) pve_guest_info{template!=\"1\"} and on (id) pve_up==1)"
    },
    {
     "expr": "sum by (id) (pve_disk_size_bytes{instance=\"$instance\"} and on (id, instance) pve_guest_info{template!=\"1\"})"
    },
    {
     "expr": "sum by (id) (\n  label_replace(\n    label_replace(\n      label_replace(\n        label_replace(\n          label_replace(\n            label_replace(\n              (\n                (node_filesystem_size_bytes{mountpoint=\"/host/root\",fstype=\"ext4\"}\n                 - node_filesystem_avail_bytes{mountpoint=\"/host/root\",fstype=\"ext4\"})\n                / node_filesystem_size_bytes{mountpoint=\"/host/root\",fstype=\"ext4\"}\n              ),\n              \"temp_name\", \"edge\", \"instance\", \"edge-vm\"\n            ),\n            \"temp_name\", \"db\", \"instance\", \"db-vm\"\n          ),\n          \"temp_name\", \"media\", \"instance\", \"media-vm\"\n        ),\n        \"temp_name\", \"dev\", \"instance\", \"dev-vm\"\n      ),\n      \"temp_name\", \"deploy\", \"instance\", \"deploy-vm\"\n    ),\n    \"temp_name\", \"observability\", \"instance\", \"observability-vm\"\n  )\n  * on(temp_name) group_left(id)\n    label_replace(pve_guest_info{template!=\"1\"}, \"temp_name\", \"$1\", \"name\", \"(.*)\")\n)"
    },
    {
     "expr": "sum by (id) ((pve_cpu_usage_ratio{instance=\"$instance\"} / pve_cpu_usage_limit) and on (id, instance) pve_guest_info{template!=\"1\"} and on(id) pve_up==1)"
    },
    {
     "expr": "sum by (id) ((rate(pve_disk_write_bytes{instance=\"$instance\"}[5m]) + rate(pve_disk_read_bytes{instance=\"$instance\"}[5m])) and on (id, instance) pve_guest_info{template!=\"1\"} and on(id) pve_up==1)"
    },
    {
     "expr": "sum by (id) ((rate(pve_network_receive_bytes{instance=\"$instance\"}[5m]) + rate(pve_network_transmit_bytes{instance=\"$instance\"}[5m])) and on (id, instance) pve_guest_info{template!=\"1\"} and on(id) pve_up==1)"
    }
   ]
  },
  {
   "title": "HIDDEN - CPUs",
   "type": "stat",
   "gridPos": { "h": 0, "w": 0, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_cpu_usage_limit and on(id) pve_node_info",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HIDDEN - Memory",
   "type": "stat",
   "gridPos": { "h": 0, "w": 0, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_memory_usage_bytes{instance=\"$instance\"} and on(id) pve_node_info",
     "legendFormat": "__auto"
    },
    {
     "expr": "pve_memory_size_bytes{instance=\"$instance\"} and on(id) pve_node_info",
     "legendFormat": "__auto"
    },
    {
     "expr": "pve_memory_size_bytes{instance=\"$instance\"} and on(id) pve_node_info",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HIDDEN - Space allocation",
   "type": "bargauge",
   "gridPos": { "h": 0, "w": 0, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_disk_size_bytes{instance=\"$instance\", id=~\"storage/.+\"} * on (id, instance) group_left(storage) pve_storage_info",
     "legendFormat": "{{storage}}"
    }
   ]
  },
  {
   "title": "HIDDEN - LXC Disk usage",
   "type": "timeseries",
   "gridPos": { "h": 0, "w": 0, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pve_disk_usage_bytes{instance=\"$instance\"} / pve_disk_size_bytes{instance=\"$instance\"} * on (id, instance) group_left(name, type) pve_guest_info{type=\"lxc\"}",
     "legendFormat": "{{name}} ({{type}})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_cpu_usage_ratio{instance=\"$instance\"} / pve_cpu_usage_limit and on(id) pve_node_info",
     "legendFormat": "Cpu"
    },
    {
     "expr": "pve_memory_usage_bytes{instance=\"$instance\"} / pve_memory_size_bytes and on(id) pve_node_info",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_disk_usage_bytes{instance=\"$instance\", id=~\"storage/.+\"} / pve_disk_size_bytes * on (id, instance) group_left(storage) pve_storage_info",
     "legendFormat": "{{storage}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "((pve_cpu_usage_ratio{instance=\"$instance\"} / pve_cpu_usage_limit) * on(id, instance) group_left(name, type) pve_guest_info) and on(id, instance) pve_up == 1",
     "legendFormat": "{{name}} ({{type}})"
    }
   ]
  },
  {
   "title": "memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(pve_memory_usage_bytes{instance=\"$instance\"} / pve_memory_size_bytes * on(id, instance) group_left(name, type) pve_guest_info) and on(id, instance) pve_up == 1",
     "legendFormat": "{{name}} ({{type}})"
    }
   ]
  },
  {
   "title": "Disk IO/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "((rate(pve_disk_write_bytes{instance=\"$instance\"}[5m]) + rate(pve_disk_read_bytes[5m])) * on(id, instance) group_left(name, type) pve_guest_info) and on(id, instance) pve_up == 1",
     "legendFormat": "{{name}} ({{type}})"
    }
   ]
  },
  {
   "title": "Network IO/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(rate(pve_network_receive_bytes{instance=\"$instance\"}[5m]) * on(id, instance) group_left(name, type) pve_guest_info) and on(id, instance) pve_up == 1",
     "legendFormat": "{{name}} RECV ({{type}})"
    },
    {
     "expr": "(rate(pve_network_transmit_bytes{instance=\"$instance\"}[5m])* on(id, instance) group_left(name, type) pve_guest_info) and on(id, instance) pve_up == 1",
     "legendFormat": "{{name}} SEND ({{type}})"
    }
   ]
  }
 ]
}