# Traefik Services - Backend Application Targets

http:
  # Services define WHERE to send traffic (the actual backend servers)
  services:
    # Authentik (local on edge VM)
    authentik-svc:
      loadBalancer:
        servers:
          - url: "http://authentik-server:9000"

    # Traefik Dashboard (local on edge VM)
    traefik-dashboard:
      loadBalancer:
        servers:
          - url: "http://10.10.10.110:8080"

    # Observability VM (10.10.10.112)
    portainer:
      loadBalancer:
        servers:
          - url: "https://10.10.10.112:9443"
        serversTransport: insecureTransport

    grafana:
      loadBalancer:
        servers:
          - url: "http://10.10.10.112:3000"

    prometheus:
      loadBalancer:
        servers:
          - url: "http://10.10.10.112:9090"

    loki:
      loadBalancer:
        servers:
          - url: "http://10.10.10.112:3100"

    alloy:
      loadBalancer:
        servers:
          - url: "http://10.10.10.112:12345"

    # VM 5: Dev (10.10.10.114)
    gitea:
      loadBalancer:
        servers:
          - url: "http://10.10.10.114:3001"

    dokploy:
      loadBalancer:
        servers:
          - url: "http://10.10.10.115:3000"

    # OLD Proxmox Services (Temporary - to be migrated)
    # Old Coolify DMO app
    dmo:
      loadBalancer:
        servers:
          - url: "http://10.10.10.51:3000"

    # Old King game (HTTP + WebSocket)
    king:
      loadBalancer:
        servers:
          - url: "http://10.10.10.51:3010"

    # Old Home Assistant (pointing to old server temporarily)
    homeassistant:
      loadBalancer:
        servers:
          - url: "http://10.10.10.13:8123"

    # VM 2: Database Host (10.10.10.111)
    minio-console:
      loadBalancer:
        servers:
          - url: "http://10.10.10.111:9001"

    minio-api:
      loadBalancer:
        servers:
          - url: "http://10.10.10.111:9000"

  # Transports - Connection Settings for Backend Servers
  serversTransports:
    # Skip TLS verification for self-signed certs (like Portainer)
    insecureTransport:
      insecureSkipVerify: true
