# Traefik Services - Backend Application Targets

http:
  # Services define WHERE to send traffic (the actual backend servers)
  services:
    # Authentik (local on edge VM)
    authentik-svc:
      loadBalancer:
        servers:
          - url: "http://authentik-server:9000"

    # Traefik Dashboard (local on edge VM)
    traefik-dashboard:
      loadBalancer:
        servers:
          - url: "http://10.10.10.110:8080"

    # AdGuard Home (local on edge VM)
    adguard:
      loadBalancer:
        servers:
          - url: "http://adguard:3000"

    # Proxmox (Hypervisor - 10.10.10.20)
    proxmox:
      loadBalancer:
        servers:
          - url: "https://10.10.10.20:8006"
        serversTransport: insecureTransport

    # Synology NAS (10.10.10.116)
    synology:
      loadBalancer:
        servers:
          - url: "https://10.10.10.116:5001"
        serversTransport: insecureTransport

    # Observability VM (10.10.10.112)
    portainer:
      loadBalancer:
        servers:
          - url: "https://10.10.10.112:9443"
        serversTransport: insecureTransport

    grafana:
      loadBalancer:
        servers:
          - url: "http://10.10.10.112:3000"

    prometheus:
      loadBalancer:
        servers:
          - url: "http://10.10.10.112:9090"

    loki:
      loadBalancer:
        servers:
          - url: "http://10.10.10.112:3100"

    alloy:
      loadBalancer:
        servers:
          - url: "http://10.10.10.112:12345"

    beszel:
      loadBalancer:
        servers:
          - url: "http://10.10.10.112:8090"

    # VM 5: Dev (10.10.10.114)
    gitea:
      loadBalancer:
        servers:
          - url: "http://10.10.10.114:3001"

    coolify:
      loadBalancer:
        servers:
          - url: "http://10.10.10.101:8000"

    # OLD Proxmox Services (Temporary - to be migrated)
    # Old Coolify DMO app
    dmo:
      loadBalancer:
        servers:
          - url: "http://10.10.10.101:3000"

    # King game - Deployed on Dokploy (10.10.10.115)
    # Frontend (Next.js) - Port assigned by Dokploy
    king:
      loadBalancer:
        servers:
          - url: "http://10.10.10.101:3010"

    # King game - Backend (WebSocket server) - Port assigned by Dokploy
    king-backend:
      loadBalancer:
        servers:
          - url: "http://10.10.10.101:3015"

    # Old Home Assistant (pointing to old server temporarily)
    homeassistant:
      loadBalancer:
        servers:
          - url: "http://10.10.10.116:8123"

    # VM 2: Database Host (10.10.10.111)
    minio-console:
      loadBalancer:
        servers:
          - url: "http://10.10.10.111:9002"

    minio-api:
      loadBalancer:
        servers:
          - url: "http://10.10.10.111:9000"

  # Transports - Connection Settings for Backend Servers
  serversTransports:
    # Skip TLS verification for self-signed certs (like Portainer)
    insecureTransport:
      insecureSkipVerify: true
